mybatis:
  mapper-locations: classpath:mappers/**/*Mapper.xml

ssh:
 settings:
   host: #ssh host
   username: #ssh username
   password: #ssh password
   port: #ssh port
 forward: 
   lhost: 127.0.0.10 #可隨意改，內部不衝突即可
   lport: 3310 #可隨意改，內部不衝突即可
   rhost: #server host
   rport: #server port

spring:
  datasource:
    url: jdbc:mysql://${ssh.forward.lhost}:${ssh.forward.lport}/{@db-name}
    username: #db username
    password: #db password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 1